before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  -
    id: geolite2lookup-darwin
    ldflags:
      - -s -w -X github.com/kunit/geolite2lookup.version={{.Version}} -X github.com/kunit/geolite2lookup.commit={{.FullCommit}} -X github.com/kunit/geolite2lookup.date={{.Date}} -X github.com/kunit/geolite2lookup/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
  -
    id: geolite2lookup-linux
    ldflags:
      - -s -w -X github.com/kunit/geolite2lookup.version={{.Version}} -X github.com/kunit/geolite2lookup.commit={{.FullCommit}} -X github.com/kunit/geolite2lookup.date={{.Date}} -X github.com/kunit/geolite2lookup/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archives:
  -
    id: geolite2lookup-archive
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: darwin
        format: zip
    files:
      - README.md
      - CREDITS
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    id: geolite2lookup-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
      - geolite2lookup-linux
    homepage: https://github.com/kunit/geolite2lookup
    maintainer: TAKAHASHI Kunihiko <kunihiko.takahashi@gmail.com>
    description: geolite2lookup is look up country/city using IP Address or hostname.
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/local/bin
    epoch: 1
